---
resources:
- name: root
  type: git
  check_every: 5m
  source:
    uri: https://github.com/sfroee/root.git
    branch: master

jobs:
- name: test-submodules
  plan:
  - get: root
    params:
      submodule_recursive: "false"
    trigger: true
  - task: simple-task
    tags: []
    timeout: 15m
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
          username: ""
          password: ""
      inputs:
        - name: root
      run:
        path: root/test.sh
